import path from "node:path";
import os from "node:os";
import fs from "fs-extra";
import { afterEach, describe, expect, it } from "vitest";
import { findRelevantContext } from "../src/relevant.js";

const tempDirs: string[] = [];

async function setupContextFiles(): Promise<string> {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "code-memory-relevant-"));
  tempDirs.push(root);
  await fs.ensureDir(path.join(root, ".ai", "domains"));

  await fs.writeFile(path.join(root, ".ai", "project-context.md"), "# Project Context\n", "utf8");
  await fs.writeJSON(
    path.join(root, ".ai", "context-index.json"),
    {
      schemaVersion: 1,
      generatedAt: "2026-05-08T00:00:00.000Z",
      rootDir: root,
      ignored: [],
      scannedFileCount: 10,
      signals: ["has-package-json", "has-tsconfig"],
      projectKinds: ["node", "typescript"],
      categories: { configs: [], source: [], tests: [], docs: [], infra: [] }
    },
    { spaces: 2 }
  );
  await fs.writeJSON(
    path.join(root, ".ai", "dependency-graph.json"),
    {
      schemaVersion: 1,
      generatedAt: "2026-05-08T00:00:00.000Z",
      rootDir: root,
      nodes: {
        "src/hooks/useAuth.ts": ["src/providers/AuthProvider.tsx", "src/services/authService.ts"],
        "src/routes/protected.ts": ["src/hooks/useAuth.ts"],
        "src/api/auth/login.ts": ["src/services/authService.ts"]
      }
    },
    { spaces: 2 }
  );

  await fs.writeFile(
    path.join(root, ".ai", "domains", "auth.md"),
    [
      "# auth domain",
      "",
      "## Important entry points",
      "",
      "- src/routes/protected.ts",
      "- src/api/auth/login.ts",
      "",
      "## Detected Concepts",
      "",
      "- authentication",
      "- dashboard",
      "",
      "## Top relevant files",
      "",
      "- src/hooks/useAuth.ts",
      "- src/services/authService.ts",
      "- src/routes/protected.ts",
      "- src/api/auth/login.ts"
    ].join("\n"),
    "utf8"
  );

  await fs.writeFile(
    path.join(root, ".ai", "domains", "frontend.md"),
    [
      "# frontend domain",
      "",
      "## Important entry points",
      "",
      "- src/pages/dashboard.tsx",
      "",
      "## Detected Concepts",
      "",
      "- dashboard",
      "",
      "## Top relevant files",
      "",
      "- src/components/Dashboard.tsx",
      "- src/hooks/useDashboard.ts"
    ].join("\n"),
    "utf8"
  );

  await fs.writeFile(
    path.join(root, ".ai", "domains", "backend.md"),
    [
      "# backend domain",
      "",
      "## Important entry points",
      "",
      "- src/api/users.ts",
      "",
      "## Detected Concepts",
      "",
      "- analytics",
      "",
      "## Top relevant files",
      "",
      "- src/services/userService.ts"
    ].join("\n"),
    "utf8"
  );

  return root;
}

afterEach(async () => {
  await Promise.all(tempDirs.map((d) => fs.remove(d)));
  tempDirs.length = 0;
});

describe("findRelevantContext", () => {
  it("prioritizes auth domain and auth-related files for authentication bug tasks", async () => {
    const root = await setupContextFiles();
    const result = await findRelevantContext(root, "fix authentication bug");

    expect(result.domains[0]).toBe("auth");
    expect(result.topFiles[0]).toMatch(/auth/i);
    expect(result.topFiles.join("\n")).toContain("useAuth");
    expect(result.topFiles.join("\n")).toContain("protected");
    expect(result.entryPoints.join("\n")).toContain("protected");
    expect(result.concepts).toContain("authentication");
  });

  it("still returns compact output when there are weak keyword matches", async () => {
    const root = await setupContextFiles();
    const result = await findRelevantContext(root, "improve reliability");

    expect(result.noStrongMatch).toBe(true);
    expect(result.domains).toEqual([]);
    expect(result.topFiles).toEqual([]);
    expect(result.entryPoints).toEqual([]);
    expect(result.concepts).toEqual([]);
    expect(result.suggestions.join("\n")).toContain("repository root");
    expect(result.suggestions.join("\n")).toContain("code-memory init");
  });

  it("ignores metadata bullets from generated domain footers", async () => {
    const root = await setupContextFiles();
    await fs.appendFile(
      path.join(root, ".ai", "domains", "auth.md"),
      "\n- Reason: Auth-related folders and file names\n- Context schema version: 1\nGenerated by CodeMemory analyze (deterministic heuristics only).\n",
      "utf8"
    );
    const result = await findRelevantContext(root, "fix authentication bug");
    const joined = result.topFiles.join("\n");
    expect(joined).not.toContain("Reason:");
    expect(joined).not.toContain("Context schema version:");
  });

  it("expands relevant files with dependency graph neighbors", async () => {
    const root = await setupContextFiles();
    const result = await findRelevantContext(root, "fix authentication bug");
    const joined = result.topFiles.join("\n");
    expect(joined).toContain("src/providers/AuthProvider.tsx");
    expect(result.topFiles.length).toBeLessThanOrEqual(12);
  });

  it("does not leak unrelated UI files into auth domain results", async () => {
    const root = await setupContextFiles();
    // Add unrelated UI files to the dependency graph as neighbors of auth files
    await fs.writeJSON(
      path.join(root, ".ai", "dependency-graph.json"),
      {
        schemaVersion: 1,
        generatedAt: "2026-05-08T00:00:00.000Z",
        rootDir: root,
        nodes: {
          "src/hooks/useAuth.ts": [
            "src/providers/AuthProvider.tsx",
            "src/services/authService.ts",
            "src/components/AdExamples.tsx",
            "src/components/BrandKitEditor.tsx"
          ],
          "src/routes/protected.ts": [
            "src/hooks/useAuth.ts",
            "src/components/CampaignSaver.tsx"
          ]
        }
      },
      { spaces: 2 }
    );
    const result = await findRelevantContext(root, "fix authentication bug");
    const joined = result.topFiles.join("\n");
    expect(joined).not.toContain("AdExamples");
    expect(joined).not.toContain("BrandKitEditor");
    expect(joined).not.toContain("CampaignSaver");
    expect(joined).toContain("useAuth");
    expect(joined).toContain("authService");
  });

  it("keeps webhook relevance focused on webhook/provider files", async () => {
    const root = await setupContextFiles();
    await fs.writeFile(
      path.join(root, ".ai", "domains", "integrations.md"),
      [
        "# integrations domain",
        "",
        "## Important entry points",
        "",
        "- src/api/webhookHandler.ts",
        "",
        "## Detected Concepts",
        "",
        "- webhook",
        "- payment",
        "",
        "## Top relevant files",
        "",
        "- src/api/webhookHandler.ts",
        "- src/services/stripeProvider.ts",
        "- src/components/GenericButton.tsx",
        "- src/components/CardPreview.tsx"
      ].join("\n"),
      "utf8"
    );
    const result = await findRelevantContext(root, "fix webhook payment processing");
    expect(result.domains).toContain("integrations");
    const joined = result.topFiles.join("\n");
    expect(joined).toContain("webhookHandler");
    expect(joined).toContain("stripeProvider");
    expect(joined).not.toContain("GenericButton");
    expect(joined).not.toContain("CardPreview");
  });

  it("admin relevance prioritizes dashboard/admin files over unrelated components", async () => {
    const root = await setupContextFiles();
    await fs.writeFile(
      path.join(root, ".ai", "domains", "admin.md"),
      [
        "# admin domain",
        "",
        "## Important entry points",
        "",
        "- src/pages/adminDashboard.tsx",
        "",
        "## Detected Concepts",
        "",
        "- dashboard",
        "- management",
        "",
        "## Top relevant files",
        "",
        "- src/pages/adminDashboard.tsx",
        "- src/services/adminService.ts",
        "- src/components/ModerationPanel.tsx",
        "- src/components/SpinnerWidget.tsx",
        "- src/components/ImagePlaceholder.tsx"
      ].join("\n"),
      "utf8"
    );
    const result = await findRelevantContext(root, "fix admin dashboard bug");
    expect(result.domains).toContain("admin");
    const joined = result.topFiles.join("\n");
    expect(joined).toContain("adminDashboard");
    expect(joined).toContain("adminService");
    expect(joined).toContain("ModerationPanel");
    expect(joined).not.toContain("SpinnerWidget");
    expect(joined).not.toContain("ImagePlaceholder");
  });

  it("warns when running relevant inside a subpackage", async () => {
    const repoRoot = await fs.mkdtemp(path.join(os.tmpdir(), "code-memory-relevant-repo-"));
    tempDirs.push(repoRoot);
    await fs.ensureDir(path.join(repoRoot, ".git"));
    await fs.writeFile(path.join(repoRoot, "package.json"), '{"name":"repo-root"}', "utf8");
    const subpkgRoot = path.join(repoRoot, "packages", "web");
    await fs.ensureDir(subpkgRoot);
    await fs.writeFile(path.join(subpkgRoot, "package.json"), '{"name":"subpkg"}', "utf8");
    await fs.ensureDir(path.join(subpkgRoot, ".ai", "domains"));

    await fs.writeFile(path.join(subpkgRoot, ".ai", "project-context.md"), "# Project Context\n", "utf8");
    await fs.writeJSON(
      path.join(subpkgRoot, ".ai", "context-index.json"),
      {
        schemaVersion: 1,
        generatedAt: "2026-05-08T00:00:00.000Z",
        rootDir: subpkgRoot,
        ignored: [],
        scannedFileCount: 2,
        signals: ["has-package-json"],
        projectKinds: ["node"],
        categories: { configs: ["package.json"], source: ["src/auth.ts"], tests: [], docs: [], infra: [] }
      },
      { spaces: 2 }
    );
    await fs.writeFile(
      path.join(subpkgRoot, ".ai", "domains", "auth.md"),
      [
        "# auth domain",
        "",
        "## Important entry points",
        "",
        "- src/auth.ts",
        "",
        "## Detected Concepts",
        "",
        "- authentication",
        "",
        "## Top relevant files",
        "",
        "- src/auth.ts"
      ].join("\n"),
      "utf8"
    );

    const result = await findRelevantContext(subpkgRoot, "fix auth bug");
    expect(result.noStrongMatch).toBe(false);
    expect(result.warnings).toContain(
      "You may be running inside a subpackage. Run from repository root for full context."
    );
  });
});
