export const CODE_MEMORY_METADATA = {
  appName: "CodeMemory",
  cliName: "code-memory",
  packageScope: "code-memory",
  corePackageName: "code-memory-core",
  cliPackageName: "code-memory-cli",
  version: "0.1.2",
  contextPaths: {
    aiDir: ".ai",
    projectContextFile: "project-context.md",
    contextIndexFile: "context-index.json",
    contextStateFile: "context-state.json",
    dependencyGraphFile: "dependency-graph.json",
    domainsDir: "domains"
  },
  generatedText: {
    projectContextFooter: "Generated by CodeMemory (deterministic static analysis only).",
    domainFooter: "Generated by CodeMemory analyze (deterministic heuristics only).",
    upToDateMessage: "Context already up to date"
  }
} as const;

export function getProjectContextFooter(): string {
  return CODE_MEMORY_METADATA.generatedText.projectContextFooter;
}

export function getDomainFooter(): string {
  return CODE_MEMORY_METADATA.generatedText.domainFooter;
}
