import path from "node:path";
import fs from "fs-extra";
import fg from "fast-glob";
import { contextIndexSchema, dependencyGraphSchema } from "./schema.js";
import { CODE_MEMORY_METADATA } from "./metadata.js";
import type { RelevantResult } from "./types.js";

interface ParsedDomainDoc {
  domain: string;
  topFiles: string[];
  entryPoints: string[];
  concepts: string[];
}

const DOMAIN_KEYWORDS: Record<string, string[]> = {
  auth: ["auth", "authentication", "login", "logout", "session", "jwt", "oauth", "protected", "rbac"],
  frontend: ["frontend", "ui", "component", "page", "route", "hook", "react", "dashboard"],
  backend: ["backend", "api", "service", "handler", "controller", "orchestr", "integration"],
  database: ["database", "db", "schema", "migration", "prisma", "supabase", "sql"],
  infrastructure: ["infra", "docker", "deploy", "ci", "k8s", "terraform"],
  testing: ["test", "spec", "e2e", "assert"],
  docs: ["docs", "readme", "guide"],
  integrations: ["webhook", "provider", "stripe", "razorpay", "api", "integration", "callback", "adapter"],
  admin: ["admin", "dashboard", "moderation", "management", "analytics"]
};

const DOMAIN_FILE_AFFINITY: Record<string, RegExp> = {
  auth: /(auth|login|session|protected|user|oauth|jwt|signup|rbac|permission)/i,
  integrations: /(webhook|provider|stripe|razorpay|adapter|integration|callback)/i,
  admin: /(admin|dashboard|moderation|management|analytics)/i,
  frontend: /(component|page|view|layout|screen|hook|ui)/i,
  backend: /(service|controller|handler|orchestr|server|api)/i,
  database: /(schema|migration|model|prisma|supabase|db|seed)/i
};

const HIGH_SIGNAL_FILE_PATTERNS = /(hook|service|provider|route|auth|session|api|webhook|controller|handler|middleware)/i;
const GENERIC_UI_PATTERNS = /(button|card|modal|icon|avatar|badge|spinner|loader|tooltip|divider|separator|input|textarea|select|checkbox|radio|toggle|tab|accordion|dropdown)/i;
const PRESENTATION_ONLY_PATTERNS = /(example|demo|sample|story|storybook|preview|placeholder|skeleton|mock)/i;

const FILE_KEYWORDS = [
  "auth",
  "login",
  "session",
  "protected",
  "route",
  "hook",
  "service",
  "api",
  "schema",
  "supabase",
  "prisma",
  "dashboard",
  "analytics"
];
const STRONG_DOMAIN_MATCH_SCORE = 6;
const STRONG_FILE_MATCH_SCORE = 10;
const SUBPACKAGE_WARNING = "You may be running inside a subpackage. Run from repository root for full context.";
const NO_STRONG_MATCH_SUGGESTIONS = [
  "Run from repository root for full context.",
  "Improve context by running `code-memory init` and `code-memory analyze`."
];

function tokenize(text: string): string[] {
  return (text.toLowerCase().match(/[a-z0-9]+/g) ?? []).filter((t) => t.length > 1);
}

function parseBulletSection(markdown: string, heading: string): string[] {
  const startPattern = new RegExp(`^##\\s+${heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*$`, "m");
  const startMatch = markdown.match(startPattern);
  if (!startMatch || startMatch.index === undefined) return [];

  const rest = markdown.slice(startMatch.index + startMatch[0].length);
  const lines = rest.split("\n");
  const bullets: string[] = [];
  for (const line of lines) {
    if (line.startsWith("## ")) break;
    if (line.startsWith("Generated by ")) break;
    const bullet = line.match(/^\s*-\s+(.+)$/);
    if (bullet) {
      const value = bullet[1].trim();
      if (value === "(none)") continue;
      if (/^(Reason|Context schema version):\s*/i.test(value)) continue;
      bullets.push(value);
    }
  }
  return bullets;
}

function parseDomainDoc(markdown: string): ParsedDomainDoc | null {
  const title = markdown.match(/^#\s+([a-z0-9-]+)\s+domain\s*$/im);
  if (!title) return null;

  return {
    domain: title[1].toLowerCase(),
    topFiles: parseBulletSection(markdown, "Top relevant files"),
    entryPoints: parseBulletSection(markdown, "Important entry points"),
    concepts: parseBulletSection(markdown, "Detected Concepts")
  };
}

function scoreDomain(taskTokens: string[], domain: ParsedDomainDoc): number {
  let score = 0;
  const keywords = DOMAIN_KEYWORDS[domain.domain] ?? [domain.domain];
  for (const token of taskTokens) {
    if (keywords.some((k) => token.includes(k) || k.includes(token))) score += 6;
  }

  const domainText = [...domain.topFiles, ...domain.entryPoints, ...domain.concepts].join(" ").toLowerCase();
  for (const token of taskTokens) {
    if (domainText.includes(token)) score += 2;
  }

  if (taskTokens.includes("bug") || taskTokens.includes("fix")) score += domain.entryPoints.length > 0 ? 1 : 0;
  return score;
}

function fileTypeWeight(file: string): number {
  const base = path.basename(file).toLowerCase();
  const value = file.toLowerCase();
  if (HIGH_SIGNAL_FILE_PATTERNS.test(base)) return 4;
  if (HIGH_SIGNAL_FILE_PATTERNS.test(value)) return 3;
  if (PRESENTATION_ONLY_PATTERNS.test(base)) return -3;
  if (GENERIC_UI_PATTERNS.test(base)) return -2;
  if (/\.(tsx|jsx)$/.test(base) && !HIGH_SIGNAL_FILE_PATTERNS.test(value)) return 0;
  return 1;
}

function getTaskRelevantDomains(taskTokens: string[], activeDomains: string[]): string[] {
  return activeDomains.filter((domain) => {
    const keywords = DOMAIN_KEYWORDS[domain] ?? [domain];
    return taskTokens.some((t) => keywords.some((k) => t.includes(k) || k.includes(t)));
  });
}

function domainAffinityScore(file: string, relevantDomains: string[]): number {
  let best = 0;
  const base = path.basename(file).toLowerCase();
  for (const domain of relevantDomains) {
    const pattern = DOMAIN_FILE_AFFINITY[domain];
    if (pattern && pattern.test(base)) best = Math.max(best, 4);
  }
  return best;
}

function scoreFile(taskTokens: string[], file: string, boostedDomain: boolean, activeDomains: string[] = []): number {
  let score = boostedDomain ? 5 : 0;
  const value = file.toLowerCase();
  for (const token of taskTokens) {
    if (value.includes(token)) score += 4;
  }
  for (const keyword of FILE_KEYWORDS) {
    if (value.includes(keyword) && taskTokens.some((t) => keyword.includes(t) || t.includes(keyword))) score += 3;
  }
  if (/(auth|login|session|protected)/.test(value) && taskTokens.some((t) => /(auth|login|session)/.test(t))) {
    score += 6;
  }
  score += fileTypeWeight(file);
  score += domainAffinityScore(file, activeDomains);
  return score;
}

function topN(items: string[], n: number): string[] {
  return [...new Set(items)].slice(0, n);
}

function isDomainRelevantDep(dep: string, relevantDomains: string[], taskTokens: string[]): boolean {
  const base = path.basename(dep).toLowerCase();
  const value = dep.toLowerCase();
  if (PRESENTATION_ONLY_PATTERNS.test(base)) return false;
  if (GENERIC_UI_PATTERNS.test(base) && !taskTokens.some((t) => value.includes(t))) return false;
  for (const domain of relevantDomains) {
    const pattern = DOMAIN_FILE_AFFINITY[domain];
    if (pattern && pattern.test(base)) return true;
  }
  if (taskTokens.some((t) => value.includes(t))) return true;
  if (HIGH_SIGNAL_FILE_PATTERNS.test(base)) return true;
  return false;
}

function expandWithDependencies(
  files: string[],
  graph: Record<string, string[]>,
  activeDomains: string[],
  taskTokens: string[]
): string[] {
  const fileSet = new Set(files);
  const expanded: string[] = [];
  const seeds = files.slice(0, 5);
  for (const seed of seeds) {
    const deps = (graph[seed] ?? []).slice(0, 4);
    for (const dep of deps) {
      if (fileSet.has(dep)) continue;
      if (!isDomainRelevantDep(dep, activeDomains, taskTokens)) continue;
      expanded.push(dep);
    }
  }
  return topN(expanded, 6);
}

async function detectSubpackageWarning(rootDir: string): Promise<string | null> {
  const cwdHasPackageJson = await fs.pathExists(path.join(rootDir, "package.json"));
  if (!cwdHasPackageJson) return null;

  let cursor = path.resolve(rootDir);
  while (true) {
    const parent = path.dirname(cursor);
    if (parent === cursor) return null;

    const hasPackageJson = await fs.pathExists(path.join(parent, "package.json"));
    const hasWorkspace = await fs.pathExists(path.join(parent, "pnpm-workspace.yaml"));
    const hasGit = await fs.pathExists(path.join(parent, ".git"));
    if (hasPackageJson || hasWorkspace || hasGit) return SUBPACKAGE_WARNING;
    cursor = parent;
  }
}

export async function findRelevantContext(rootDir: string, task: string): Promise<RelevantResult> {
  const aiDir = path.join(rootDir, CODE_MEMORY_METADATA.contextPaths.aiDir);
  const projectContextPath = path.join(aiDir, CODE_MEMORY_METADATA.contextPaths.projectContextFile);
  const indexPath = path.join(aiDir, CODE_MEMORY_METADATA.contextPaths.contextIndexFile);
  const domainsGlob = path.join(
    CODE_MEMORY_METADATA.contextPaths.aiDir,
    CODE_MEMORY_METADATA.contextPaths.domainsDir,
    "*.md"
  );
  const graphPath = path.join(aiDir, CODE_MEMORY_METADATA.contextPaths.dependencyGraphFile);
  const warning = await detectSubpackageWarning(rootDir);
  const warnings = warning ? [warning] : [];

  // Ensure required context files exist and are valid.
  await fs.readFile(projectContextPath, "utf8");
  const indexRaw = await fs.readJSON(indexPath);
  contextIndexSchema.parse(indexRaw);
  const graph = (await fs.pathExists(graphPath))
    ? dependencyGraphSchema.parse(await fs.readJSON(graphPath)).nodes
    : {};

  const domainFiles = await fg([domainsGlob], { cwd: rootDir, onlyFiles: true, dot: true });
  const parsed: ParsedDomainDoc[] = [];
  for (const file of domainFiles.sort()) {
    const markdown = await fs.readFile(path.join(rootDir, file), "utf8");
    const doc = parseDomainDoc(markdown);
    if (doc) parsed.push(doc);
  }

  const taskTokens = tokenize(task);
  const rankedDomains = parsed
    .map((d) => ({ domain: d.domain, score: scoreDomain(taskTokens, d), doc: d }))
    .filter((d) => d.score > 0)
    .sort((a, b) => b.score - a.score || a.domain.localeCompare(b.domain));

  const selectedDomains = (rankedDomains.length > 0 ? rankedDomains : parsed.map((d) => ({ domain: d.domain, score: 0, doc: d })))
    .slice(0, 4);

  const domainNames = selectedDomains.map((d) => d.domain);
  const domainSet = new Set(domainNames);
  const relevantDomains = getTaskRelevantDomains(taskTokens, domainNames);

  const allFilesScored: Array<{ file: string; score: number }> = [];
  for (const d of parsed) {
    for (const file of d.topFiles) {
      allFilesScored.push({
        file,
        score: scoreFile(taskTokens, file, domainSet.has(d.domain), relevantDomains)
      });
    }
  }

  const topFiles = allFilesScored
    .filter((f) => f.score > 0)
    .sort((a, b) => b.score - a.score || a.file.localeCompare(b.file))
    .map((f) => f.file);
  const strongDomainMatches = rankedDomains.filter((d) => d.score >= STRONG_DOMAIN_MATCH_SCORE);
  const strongFileMatches = allFilesScored.filter((f) => f.score >= STRONG_FILE_MATCH_SCORE);
  const hasStrongMatch = strongDomainMatches.length > 0 || strongFileMatches.length > 0;

  const selectedDocs = parsed.filter((d) => domainSet.has(d.domain));
  const entryPoints = topN(
    selectedDocs
      .flatMap((d) => d.entryPoints)
      .sort((a, b) => scoreFile(taskTokens, a, true, relevantDomains) - scoreFile(taskTokens, b, true, relevantDomains))
      .reverse(),
    8
  );
  const concepts = topN(
    selectedDocs
      .flatMap((d) => d.concepts)
      .sort((a, b) => scoreFile(taskTokens, a, true, relevantDomains) - scoreFile(taskTokens, b, true, relevantDomains))
      .reverse(),
    8
  );

  const baseTopFiles = topN(topFiles, 8);
  const expandedFiles = expandWithDependencies(baseTopFiles, graph, relevantDomains, taskTokens);
  const combinedTopFiles = topN([...baseTopFiles, ...expandedFiles], 12);

  if (!hasStrongMatch) {
    return {
      task,
      domains: [],
      topFiles: [],
      entryPoints: [],
      concepts: [],
      noStrongMatch: true,
      warnings,
      suggestions: [...NO_STRONG_MATCH_SUGGESTIONS]
    };
  }

  return {
    task,
    domains: domainNames,
    topFiles: combinedTopFiles,
    entryPoints,
    concepts,
    noStrongMatch: false,
    warnings,
    suggestions: []
  };
}
